# Generated by Django 4.2.3 on 2023-07-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('status', models.BooleanField()),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
